### PR TITLE
Fix disabled field when add ‘disabled’ attribute to widget

### PR DESCRIPTION
**Pull request by tam0407**
For #163

### CODE REVIEW

**Comment by mlavin** [comment]
This looks like a good start but I don't think this addresses the last point from the issue:

> 3.) the user can still remove items from the selection

**Comment by tam0407** [comment]
Ok thanks, let me take a look

**Comment by tam0407** [comment]
@mlavin I've just added some code to disable the remove button from deck item.

**Comment by mlavin** [comment]
Looks good to me. Thank you again for all of your contributions :heart:

**Pull request merged**
