### PR TITLE
Add Django 3.0 support

### PR DESCRIPTION
**Pull request by kluchrj**
Drops support for python 2, and fixes various deprecation warnings.

Also adds python 3.7 + 3.8, and Django 2.2 to tox.

### CODE REVIEW

**Comment by tzwaan** [comment]
Is there a reason why this has not been reviewed/merged yet?
The package currently does not support django 3.0 despite advertising it does in the readme.

**Comment by tzwaan** [comment]
Great, Thanks!

**Comment by domdinicola** [comment]
@mlavin any chance to get a new release?
latest pypi 1.2.1 doesn't support django 3.0

**Comment by Kladdy** [comment]
Ping on this one, a new release would be appreciated as the current version doesnt support django 3.0, expecially when django.utils.six doesnt exist anymore

**Comment by daviddwmd** [comment]
@mlavin any chance to get a new release?
latest pypi 1.2.1 doesn't support django 3.0

**Comment by domdinicola** [comment]
We have been asking this for a while..  tbh I don't see this happening :/

**Comment by daviddwmd** [comment]
This looks like a great project - does anyone want to fork it and be the new maintainer?

**Comment by mlavin** [comment]
If anyone wants to take over as maintainer I'm happy to facilitate that transfer. This isn't a priority for me.

**Comment by domdinicola** [comment]
feel free to add my as maintainer/owner (also in pypi).
I can manage packaging, looking at PRs and upload packages on pypi

**Comment by mlavin** [comment]
Added to the repo. Are you also @domdinicola on PyPi or do you have a different username?

**Comment by domdinicola** [comment]
hi @mlavin, thanks.
On Pypi I'm dom.dinicola .

Thanks a lot

**Comment by domdinicola** [comment]
version 1.3.0 released

**Comment by mlavin** [comment]
🎉 🎉 🎉

**Comment by daviddwmd** [comment]
Thank you both!!!

**Pull request merged**
