### PR TITLE
Django 2.0 support

### PR DESCRIPTION
**Pull request by vkurup**
This is mostly #190, with 1 commit added to add documentation and minor tox/travis configuration changes. There is one [python warning remaining](https://docs.djangoproject.com/en/2.0/ref/forms/api/#configuring-the-rendering-of-a-form-s-widgets), which is probably best dealt with when we drop Django <1.11 support:

```
boundfield.py:41: RemovedInDjango21Warning: Add the `renderer` argument to the render() method of <class 'selectable.forms.widgets.AutoCompleteSelectMultipleWidget'>. It will be mandatory in Django 2.1.
```

:crossed_fingers: that this works on Travis (not sure if deadsnakes will work?)

### CODE REVIEW

**Comment by mlavin** [comment]
Thanks for this update! Is there any reason to keep <1.11 support around? Seems like it can all just :fire:

**Comment by vkurup** [comment]
awesome, I love deleting things!! I'll ping you when it's updated.

**Comment by kluchrj** [comment]
One thing I've found while testing this:

https://github.com/mlavin/django-selectable/blob/494013a6e5e1336fd841edfb43f92eb146138014/selectable/decorators.py#L53

https://github.com/mlavin/django-selectable/blob/494013a6e5e1336fd841edfb43f92eb146138014/selectable/decorators.py#L61

Django 2.0 no longer supports the `user.is_authenticated()` method, this needs to be changed to a property (`user.is_authenticated`).

**Comment by mlavin** [comment]
That's a good point @kluchrj. I don't think that is caught by the test suite because of the heavy use of Mocks. That should also be addressed.

**Comment by kluchrj** [comment]
@vkurup, not sure if you're still working on this, but I've stripped out all the <1.11 compat and fixed the issue mentioned above in my fork: https://github.com/kluchrj/django-selectable/tree/deprecations

Should I submit a pull request to replace this one?

**Comment by vkurup** [comment]
I have not had time to update this, so yes, please do submit a PR. Thanks!

**Comment by vkurup** [comment]
Superceded by #199

**Pull request closed without merging**
