### PR TITLE
Django 1.11 fixes

### PR DESCRIPTION
**Pull request by spookylukey**
This fixes the main issues described in #187 

There are a few other tiny fixes/improvements to the tests that I hit along the way (in separate commits), but mainly I've tried to do it without rewriting the tests. The tests for the widget attributes did need changing significantly i.e. they now render the widgets, rather than call `build_attrs` on them, for reasons described in the commit messages. I tried to write the tests in ways that are future proof (i.e. don't assume that each widget will render a single HTML element), which is where some of the complexity comes from e.g. the `AttrMap` class.

### CODE REVIEW

**Comment by spookylukey** [comment]
I've now fixed the remaining issues with this, added and fixed some tests, and fixed another warning in the test suite. I've also tested `AutoCompleteSelectMultipleField` in a real project running Django 1.11, which found some of the additional issues, but they are now fixed.

**Comment by mlavin** [comment]
This is :sparkles: amazing :sparkles: ! This compatibility shim is pretty complex but it's just a transition and can be dropped once < 1.11 support is eventually dropped. I don't really have any other feedback at the moment but I'm going to need a little more time to digest these changes and familiarize myself more with the 1.11 APIs. Thank you :heart: :heart: :heart:

**Comment by spookylukey** [comment]
@mlavin agreed that it is complex, more complex than I had hoped, but I couldn't find an easier way. 

For the first main fix, the complexities came from:
1) the fact that we need to both provide `build_attrs` correctly so that it can be called from `render` in different Django versions,
2) the need to call `build_attrs` ourselves in our own `render` methods.

Additionally, there was:
3) the fact that for `MultiWidget` in Django 1.11, the `render` method of the subwidgets doesn't get called, so we need `get_context` instead.
4) test coverage didn't pick up item 3, I had to add tests for 'title'
5) some of the widget tests weren't plumbed the way that the fields work in practice, so those also had to be fixed.

Sorry for the complexity, as you say some of it will disappear in the future!

**Comment by mlavin** [comment]
Had a chance to more thoroughly review this and I think this is great. Thank you again for all of your work @spookylukey

**Pull request merged**
