### PR TITLE
upgrade for django2

### PR DESCRIPTION
**Pull request by arthru**

### CODE REVIEW

**Comment by arthru** [comment]
I don't know why travis fails with python 3.3... Some help here would be welcome !

**Comment by PetrDlouhy** [comment]
@arthru Support for Python 3.3 was dropped in Travis-CI.

**Comment by arthru** [comment]
I merged and resolved conflicts and now travis is successful !

**Comment by tkh** [comment]
Hey guys; looks like this one might be redundant now after https://github.com/mlavin/django-selectable/pull/199/ was merged in?

Fairly keen for Django 2.0 support so just wanted to bump some attention here.

**Comment by mlavin** [comment]
Yes this has been covered by #199

**Pull request closed without merging**
